spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miracle?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: miracle
    password: sprinters
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  logging:
    level:
      org.hibernate.SQL: debug