def AWS_REGION = "ap-northeast-2"
def AWS_ACCOUNT_ID = "014276069644"

def S3_CREDENTIAL_ID = "miracle_s3_user"
def JENKINS_ECR_CREDENTIAL_ID = "jenkins_ecr_user"

def APP_NAME = "game-publisher"
def ECR_REPO = "014276069644.dkr.ecr.ap-northeast-2.amazonaws.com/game-publisher"

podTemplate(
    label: 'docker-build',
    containers: [
        containerTemplate(
            name: 'docker',
            image: 'docker',
            command: 'cat',
            ttyEnabled: true
        ),
        containerTemplate(
            name: 'argo',
            image: 'argoproj/argo-cd-ci-builder:latest',
            command: 'cat',
            ttyEnabled: true
        )
    ],
    volumes: [
         hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
    ]
) {
    node('docker-build') {
        try {
            stage('Checkout') {
                checkout scm
            }

            stage('Append .yml files') {
                def bucketName = "miracle-yml-bucket"
                def adminResourcesDir = "${env.WORKSPACE}/adapter/application-admin/src/main/resources/"
                def userResourcesDir = "${env.WORKSPACE}/adapter/application-user/src/main/resources/"

                withAWS(region: "${AWS_REGION}", credentials: "${S3_CREDENTIAL_ID}") {
                    s3Download(file: 'game/game-user.yml', bucket: "${bucketName}", path: "${userResourcesDir}")
                    s3Download(file: 'game/game-admin.yml', bucket: "${bucketName}", path: "${adminResourcesDir}")
                }
            }

            stage('Test') {
                dir("${env.WORKSPACE}") {
                    sh "chmod 755 ./gradlew"
                    sh "./gradlew test"
                }
            }

            stage('Build the application') {
                dir("${env.WORKSPACE}") {
                    sh "cd adapter/application-admin"
                    sh "chmod 755 ./gradlew"
                    sh "./gradlew build"
                }
            }

            stage('Docker build and push') {
                dir("${env.WORKSPACE}/adapter/application-admin") {
                    container('docker') {
                        docker.withRegistry("https://${ECR_REPO}", "ecr:${AWS_REGION}:${JENKINS_ECR_CREDENTIAL_ID}") {
                            image = docker.build("${ECR_REPO}:latest")
                            image.push()
                        }
                    }
                }
            }

            slackSend(
                channel: 'deployment-notification',
                color: 'good',
                message: "[Successful] Job:${env.JOB_NAME}, Build num:${env.BUILD_NUMBER} (<${env.RUN_DISPLAY_URL}|open job detail>)"
            )
        } catch (Exception e) {
            slackSend(
                channel: 'deployment-notification',
                color: 'danger',
                message: "[Failed] Job:${env.JOB_NAME}, Build num:${env.BUILD_NUMBER} @channel (<${env.RUN_DISPLAY_URL}|open job detail>)"
            )

            throw e
        }
    }
}
