podTemplate(
    label: 'docker-build',
    containers: [
        containerTemplate(
            name: 'docker',
            image: 'docker',
            command: 'cat',
            ttyEnabled: true
        ),
        containerTemplate(
            name: 'argo',
            image: 'argoproj/argo-cd-ci-builder:latest',
            command: 'cat',
            ttyEnabled: true
        )
    ],
    volumes: [
         hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
    ]
) {
    node('docker-build') {
        def AWS_REGION = "ap-northeast-2"
        def AWS_ACCOUNT_ID = "014276069644"

        def APP_NAME = "game-publisher"
        def ECR_REPO = "014276069644.dkr.ecr.ap-northeast-2.amazonaws.com/game-publisher"

        try {
            stage('Checkout') {
                checkout scm
            }

            stage('Test') {
                dir("${env.WORKSPACE}") {
                    sh "chmod 755 ./gradlew"
                    sh "./gradlew test"
                }
            }

            stage('Build the application') {
                dir("${env.WORKSPACE}") {
                    sh "cd adapter/application-admin"
                    sh "chmod 755 ./gradlew"
                    sh "./gradlew build"
                }
            }

            stage('Build docker image of the admin application') {
                container('docker') {
                    dir("${env.WORKSPACE}") {
                        sh "cd adapter/application-admin && docker build -t ${APP_NAME} ."
                        sh "docker tag ${APP_NAME}:latest ${ECR_REPO}:latest"
                    }
                }
            }

            stage('ECR Upload') {
                container('docker') {
                    withCredentials([[
                    credentialsId: "jenkins_ecr_user",
                    accessKeyVariable: "AWS_ACCESS_KEY_ID",
                    secretKeyVariable: "AWS_SECRET_ACCESS_KEY"
                    ]]) {
                        sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
                        sh "docker push ${ECR_REPO}:latest"
                    }
                }
            }

            slackSend(
                channel: 'deployment-notification',
                color: 'good',
                message: "[Successful] Job:${env.JOB_NAME}, Build num:${env.BUILD_NUMBER} (<${env.RUN_DISPLAY_URL}|open job detail>)"
            )
        } catch (Exception e) {
            slackSend(
                channel: 'deployment-notification',
                color: 'danger',
                message: "[Failed] Job:${env.JOB_NAME}, Build num:${env.BUILD_NUMBER} @channel (<${env.RUN_DISPLAY_URL}|open job detail>)"
            )

            throw e
        }
    }
}
